name: Update outpdated dependencies

on:
  schedule:
    # At 00:00 on every day-of-month from 1 through 7 if it's on every 7th day-of-week in March, June, September, and December.
    - cron: 0 0 1-7 3,6,9,12 */7

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Update dependencies
        run: |
          npx -p npm-check-updates ncu -u
          npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: '[chore] Update dependencies'
            committer: GitHub <noreply@github.com>
            author: actions-bot <actions-bot@users.noreply.github.com>
            title: Update dependencies
            body: |
              Dependency updates

              Auto-generated by actions-bot
            branch: update-dependencies-${{ steps.date.outputs.date }}
